#!/bin/sh
if [ $# -lt 1 ]       # If the number of arguments in not 1
then
	echo "ERROR : Bad number of arguments" 2>&1
    echo "Sort a single BAM file or all the BAM files present in the given directory."
    echo "  Usage: "
    echo "    sortbam <file_name|dir_path> [<thread>]"
    echo "      <file_name|dir_path> = path to the BAM file to convert or to the root folder of the SAM files to convert."
    echo "      <thread>             = (optional) number of processors to use. Used only if a folder is given as first argument."
    echo ""
    echo "  Example:"
    echo "    * sort foo.bam, type 'sortbam foo.bam'"
    echo "    * to sort all the BAM files in /home/foouser/test using 4 processors, type 'sortbam /home/foouser/test 4'"
    exit 1
fi

FILE=$1

if [ -f $FILE ];
then
java -jar $PICARD_DIR/SortSam.jar SO=coordinate I=$FILE O=`echo "$FILE" | sed s/\\\.bam//`_SORTED_PICARD_COOR.bam

else

  if [ $# -eq 2 ]
  then
     THREAD=$2
  else
     THREAD=1
  fi

find $FILE -type f -name '*.bam' -print0 | xargs -0 -P$THREAD -L1 -t -I{} sh -c 'java -jar $PICARD_DIR/SortSam.jar SO=coordinate I="$@" O=`echo "$@" | sed s/\\\.bam//`_"$0".bam' SORTED_PICARD_COOR {}

fi
