##############
# This script performs linear regression of a bed file that was generated by the NGS profiling package using boxplots of ratio with ggplots.
# Descostes dec 2016
##############

library("car");
library("NGSprofiling");

################
# PARAMETERS
################


bed_file_vec <- c("/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-0-2633-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-11619-18391-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-131827-2320934-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-18391-28545-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-2633-6578-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-28545-43406-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-43406-69720-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-6578-11619-orderedByRatio.bed",
		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-69720-131827-orderedByRatio.bed")  

output_folder <- "/home/descostes/Documents/analysis/ctd-JC/linear_regression/siARS2PolII_deciledivision/";

comparison_title <- "length_vs_ratio";


#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-0-2633-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-11619-18391-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-131827-2320934-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-18391-28545-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-2633-6578-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-28545-43406-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-43406-69720-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-6578-11619-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/decile/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-69720-131827-orderedByRatio.bed"




#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-0-500-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-1000-2000-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-2000-4000-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-4000-6000-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-500-1000-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-6000-8000-orderedByRatio.bed",
#"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siARS2PolII-8000-NA-orderedByRatio.bed"

#c("/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-0-500-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-1000-2000-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-2000-4000-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-4000-6000-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-500-1000-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-6000-8000-orderedByRatio.bed",
#		"/home/descostes/Documents/analysis/ctd-JC/boxplots/violinplot/normal_division/hela/percentage_100/0_NA/GRP_AVG_LEVEL_TOTAL/exprshela_gene.value/files_ordered_by_ratio/siFFLPolII-8000-NA-orderedByRatio.bed");

################




##############
# MAIN
##############

checkingOutputFolder(output_folder);

# Reading input files

bed_file_list <- list();

bed_file_list <- lapply(bed_file_vec, function(x){cat(x,"\n");fi <- read.table(x,stringsAsFactors=F, header=T); return(fi)});

# Combining all files

bed_file_matrix <- do.call(rbind, bed_file_list);

#Retrieving length and ratio

length_vec <- bed_file_matrix[,3] - bed_file_matrix[,2];
ratio_vec <- bed_file_matrix[,5];
ratio_length_df <- data.frame(length = length_vec, ratio = ratio_vec);

#perform linear regression

result_lm <- lm(length~ratio, data = ratio_length_df);
result_lm_log10 <- lm(length~ratio, data = log10(ratio_length_df));

# Print results

summary_result_lm <- summary(result_lm);
summary_result_lm_log10 <- summary(result_lm_log10);

# Residual diagnostic plot (homoscedasticity assumption):
# A residual plot is a graph that shows the residuals on the vertical axis and the independent variable on the horizontal axis. If the points in a residual plot are randomly dispersed around the horizontal axis, a linear regression model is appropriate for the data; otherwise, a non-linear model is more appropriate.
# Also the test should not be significant

test <- residualPlots(result_lm, plot=FALSE);

png(filename=paste(output_folder, "residual_plot.png",sep=""), width = 600, height = 600, bg = "transparent")
residualPlots(result_lm, main=paste("Pr(>|t|)=", test[1,2], ",", test[2,2],sep=" "));
dev.off();

test_log10 <- residualPlots(result_lm_log10, plot=FALSE);

png(filename=paste(output_folder, "residual_plot_log10.png",sep=""), width = 600, height = 600, bg = "transparent")
residualPlots(result_lm_log10, main=paste("Pr(>|t|)=", test_log10[1,2], ",", test_log10[2,2],sep=" "));
dev.off();


# QQplot to test for the normality of the residuals
# The points should be in between the dashed lines and follow a diagonal (be carefull with outliers).

png(filename=paste(output_folder, "qqplot_normality.png",sep=""), width = 600, height = 600, bg = "transparent")
qqPlot(result_lm);
dev.off();

png(filename=paste(output_folder, "qqplot_normality_log10.png",sep=""), width = 600, height = 600, bg = "transparent")
qqPlot(result_lm_log10);
dev.off();


# Plotting the relationship indicating R, R^2 and p-value

png(filename=paste(output_folder, comparison_title,".png",sep=""), width = 600, height = 600, bg = "transparent")
plot(length_vec, ratio_vec, type="p", pch=".", main= paste("length_vs_ratio: adj Rsq = ", round(summary_result_lm$adj.r.squared, digits=2), sep=""), xlab="length", ylab="ratio", las=1)
abline(result_lm,col="red");
dev.off();

png(filename=paste(output_folder, comparison_title,"-log10.png",sep=""), width = 600, height = 600, bg = "transparent")
plot(log10(length_vec), log10(ratio_vec), type="p", pch=".", main= paste("length_vs_ratio: adj Rsq = ", round(summary_result_lm$adj.r.squared, digits=2), sep=""), xlab="log10(length)", ylab="log10(ratio)", las=1)
abline(result_lm_log10,col="red");
dev.off();

